#Identificadores
1 - Deve começar com uma "letra"
2 - Os próximos caracteres deve ser "letras ou números"
3 - "Não" pode utilizar nenhum "símbolo" exceto "_"
4 - identificadores "não" pode conter "espaço" em branco
5 - "Não" pode conter letras com "acentos"
6 - "não" pode ser uma palavra "reservada"

# Tipos Primitivos

// INTEIRO - guarda apenas números inteiros Ex: 1 3 - 5 198 0 \\
// REAL - são os que possuem parte fracionaria Ex: 0.5 5.0 9.8 -77.3 3.1415 \\
// CARACTERE - Tudo que é colocado em aspas Ex: "Deivid" "Algoritmo" "123" \\
// LOGICO - "Verdadeiro" e "Falso"